Feat/base registration
Zmicer-Yafremau/airways pull request #11
Opened 2023-04-30 10:37 UTC by Zmicer-Yafremau

#### 🤔 This is a ...

- [x] New feature
- [ ] Bug fix
- [ ] Performance optimization
- [ ] Refactoring
- [ ] Test Case
- [ ] Documentation update
- [ ] Other

#### 🔗 Related trello card link

[Describe the source of requirement, like related issue link](https://trello.com/c/TVmOAEQV/7-base-registration)

#### 💡 Background and solution

Add base registration sketch with some basic validation

#### 📷 Screenshots

![image](https://user-images.githubusercontent.com/62570834/235348537-057f510d-88b4-43b3-8ed4-852cbba81a09.png)

2023-04-30 12:35 UTC, ShArPman13 approved these changes

2023-05-01 07:06 UTC, kubarenatioN requested changes
In general everything is good. But I require some changes from you, please take a look at my comments and in case of any issues/questions - DM me in discord/tg

2023-05-01 07:06 UTC, kubarenatioN commented on src/app/components/header/header.component.ts
> +  styleUrls: ["./header.component.scss"],
It's better to use single-quotes. Seems like we forget to setup prettier for this project. Let's leave it for now as it is, but we will need to setup prettier anyway, the sooner the better

2023-05-01 07:06 UTC, kubarenatioN commented on src/app/components/header/header.component.ts
> +  public launhAuthDialog() {
Typo, don't forget to correct it to "laun**c**h..." and even better just "openAuthDialog", launch is more about Elon Mask & rockets 😂

2023-05-01 07:06 UTC, kubarenatioN commented on src/app/modules/auth/components/login/login.component.ts
> +      r_email: ["", [Validators.required, Validators.email]],
Try to avoid this syntax, in JS we write camelCase -> rEmail, regForm, loginForm, but better to use a little bit more expanded names for keys. 
Also use single quotes - it's a standard rule.

2023-05-01 07:06 UTC, kubarenatioN commented on src/app/modules/auth/components/login/login.component.ts
> +  public phoneValidator(control: FormControl): ValidationErrors | null {
For validation functions, let's move them in separate file called "validators", and just export them into this component. We may need them somewhere else in future and also will make this file cleaner and leave only component's logic

2023-05-01 07:06 UTC, kubarenatioN commented on src/app/modules/auth/components/login/login.component.ts
Look. This component named `login`, but it contains 2 tabs with sub-components - one is `registration`, another is ... `login` again. Also, I see empty `registration` component in this PR. 
So, right now we have quite messy structure for authorization feature. We need to tidy it up.
My proposition is:
1.  create component called `auth-modal`. It will be our content of Angular Dialog Component, but at the same time - wrapper for two inner components (login & registration) 
*Perfect place for tabs [register][login]
2. move current file logic (registration logic) to `register` component
3. leave this file without login logic as it's scope of another feature.

2023-05-01 07:07 UTC, kubarenatioN commented on src/app/components/header/header.component.ts
> +  styleUrls: ["./header.component.scss"],
You don't have to change all `"_"` by `'_'` right now, just keep it in mind and may be change your local settings in code editor to use single quotes.

2023-05-01 11:14 UTC, Zmicer-Yafremau commented on src/app/components/header/header.component.ts
> +  styleUrls: ["./header.component.scss"],
I've changed the rule and refactor the code to have single quotes

2023-05-01 11:16 UTC, Zmicer-Yafremau commented on src/app/components/header/header.component.ts
> +  public launhAuthDialog() {
done

2023-05-01 11:21 UTC, Zmicer-Yafremau commented on src/app/modules/auth/components/login/login.component.ts
> +      r_email: ["", [Validators.required, Validators.email]],
done

2023-05-01 12:04 UTC, Zmicer-Yafremau commented on src/app/modules/auth/components/login/login.component.ts
> +  public phoneValidator(control: FormControl): ValidationErrors | null {
done

2023-05-01 12:04 UTC, Zmicer-Yafremau commented on src/app/modules/auth/components/login/login.component.ts
done

2023-05-01 21:46 UTC, kubarenatioN approved these changes
Great job!

2023-05-01 21:48 UTC, merged